name: Node.js Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t philip07/reactapp:${{ 1.0 }} .
          docker login -u philip07 -p ${{ secrets.DOCKER_PASSWORD }}
          docker push philip07/reactapp:${{ github.sha }}

      - name: Deploy to server
        run: |
          ssh user@your-server 'docker pull philip07/reactapp:${{ 1.0 }}'
          ssh user@your-server 'docker run -d -p 80:80 philip07/reactapp:${{ 1.0 }}'

