name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Updated to v2

      - name: Setup Node.js
        uses: actions/setup-node@v2  # Updated to v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm ci  # Use npm ci for clean installs in CI environments

      - name: Build application
        run: |
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Static Server
        uses: actions/checkout@v2

      - name: Install Serve
        run: npm install -g serve

      - name: Deploy
        run: |
          serve -s build
